<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>CAD-WPF</AssemblyName>
    <RootNamespace>CadWpf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CadCommon\CadCommon.csproj" />
    <ProjectReference Include="..\OcctNet\OcctNet.csproj" />
    <ProjectReference Include="..\OcctNet.Wpf\OcctNet.Wpf.csproj" />
  </ItemGroup>
</Project>
