<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OcctNet\OcctNet.csproj" />
    <ProjectReference Include="..\..\src\OcctScript.Domain\OcctScript.Domain.csproj" />
    <ProjectReference Include="..\..\src\OcctScript.Expressions\OcctScript.Expressions.csproj" />
    <ProjectReference Include="..\..\src\OcctScript.Application\OcctScript.Application.csproj" />
    <ProjectReference Include="..\..\src\OcctScript.Geometry\OcctScript.Geometry.csproj" />
  </ItemGroup>
</Project>
