using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using System.Xml.Linq;

internal static class Program
{
    private sealed record AssemblyInput(string Name, string DllPath, string XmlPath);

    private sealed class XmlDocs
    {
        private readonly Dictionary<string, string> _members;

        public XmlDocs(string path)
        {
            _members = new(StringComparer.Ordinal);
            if (!File.Exists(path)) return;

            var document = XDocument.Load(path);
            foreach (var member in document.Descendants("member"))
            {
                var name = (string?)member.Attribute("name");
                if (string.IsNullOrWhiteSpace(name)) continue;
                var summary = Normalize(member.Element("summary")?.Value);
                if (!string.IsNullOrWhiteSpace(summary)) _members[name] = summary;
            }
        }

        public string Type(Type type) => Get("T:" + XmlTypeName(type));
        public string Field(Type type, FieldInfo field) => Get("F:" + XmlTypeName(type) + "." + field.Name);
        public string Property(Type type, PropertyInfo property) => Get("P:" + XmlTypeName(type) + "." + property.Name);
        public string Event(Type type, EventInfo value) => Get("E:" + XmlTypeName(type) + "." + value.Name);
        public string Method(Type type, MethodBase method)
        {
            var name = method.IsConstructor ? "#ctor" : method.Name;
            var prefix = "M:" + XmlTypeName(type) + "." + name;
            var exact = _members.FirstOrDefault(pair => pair.Key == prefix || pair.Key.StartsWith(prefix + "(", StringComparison.Ordinal));
            return exact.Value ?? string.Empty;
        }

        private string Get(string key) => _members.TryGetValue(key, out var value) ? value : string.Empty;
        private static string XmlTypeName(Type type) => (type.FullName ?? type.Name).Replace('+', '.');
        private static string Normalize(string? value) => string.IsNullOrWhiteSpace(value)
            ? string.Empty
            : string.Join(" ", value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
    }

    private sealed record Language(
        string Code,
        string ApiTitle,
        string GeneratedNotice,
        string AssemblyLabel,
        string NamespaceLabel,
        string DeclarationLabel,
        string DescriptionLabel,
        string ConstructorsLabel,
        string PropertiesLabel,
        string EventsLabel,
        string MethodsLabel,
        string FieldsLabel,
        string ParametersLabel,
        string ReturnsLabel,
        string InheritedLabel,
        string NoneText,
        string IndexIntro,
        string TypeCountLabel,
        string MemberCountLabel,
        string FallbackTypeDescription,
        string FallbackMemberDescription);

    private static readonly Language Zh = new(
        "zh-CN", "OcctCSharpBridge 完整 API 参考", "此目录由 `tools/OcctApiDocsGenerator` 从公开程序集与 XML Documentation 自动生成，请勿手工维护 `reference` 下的文件。",
        "程序集", "命名空间", "声明", "说明", "构造函数", "属性", "事件", "方法", "字段 / 枚举值", "参数", "返回值", "继承", "无",
        "本索引覆盖 Binary SDK 的全部公开 .NET 类型。每个类型页面列出声明、构造函数、属性、事件、方法、参数与返回类型。", "公开类型数", "公开成员数",
        "公开 API 类型。具体语义、所有权和生命周期约束以类型声明、成员签名及对应专题文档为准。", "公开 API 成员。参数与返回类型见下方签名。"
    );

    private static readonly Language En = new(
        "en-US", "OcctCSharpBridge Complete API Reference", "This directory is generated by `tools/OcctApiDocsGenerator` from the public assemblies and XML documentation. Do not hand-edit files under `reference`.",
        "Assembly", "Namespace", "Declaration", "Description", "Constructors", "Properties", "Events", "Methods", "Fields / Enum Values", "Parameters", "Returns", "Inheritance", "None",
        "This index covers every public .NET type in the Binary SDK. Each type page lists its declaration, constructors, properties, events, methods, parameters, and return types.", "Public types", "Public members",
        "Public API type. See the declaration, member signatures, and related conceptual documentation for semantics, ownership, and lifetime constraints.", "Public API member. See the signature below for parameters and return type."
    );

    public static int Main(string[] args)
    {
        try
        {
            var options = ParseArgs(args);
            var root = Path.GetFullPath(options.GetValueOrDefault("repository-root") ?? Directory.GetCurrentDirectory());
            var configuration = options.GetValueOrDefault("configuration") ?? "Release";
            var contractPath = Path.Combine(root, "bridge-contract.json");
            if (!File.Exists(contractPath)) throw new FileNotFoundException("bridge-contract.json was not found.", contractPath);

            const string targetFramework = "net10.0-windows";
            var inputs = new[]
            {
                Input(root, "OcctNet", "src/OcctNet", configuration, targetFramework),
                Input(root, "OcctNet.WinForms", "src/OcctNet.WinForms", configuration, targetFramework),
                Input(root, "OcctNet.Wpf", "src/OcctNet.Wpf", configuration, targetFramework),
                Input(root, "OcctNet.Avalonia", "src/OcctNet.Avalonia", configuration, targetFramework)
            };

            foreach (var input in inputs)
            {
                if (!File.Exists(input.DllPath)) throw new FileNotFoundException($"Managed assembly was not found: {input.DllPath}");
            }

            var assemblyPaths = inputs.ToDictionary(input => input.Name, input => input.DllPath, StringComparer.OrdinalIgnoreCase);
            AssemblyLoadContext.Default.Resolving += (_, assemblyName) =>
            {
                if (assemblyName.Name is not null && assemblyPaths.TryGetValue(assemblyName.Name, out var dependency))
                    return AssemblyLoadContext.Default.LoadFromAssemblyPath(dependency);
                return null;
            };

            var loaded = inputs.Select(input => (Input: input, Assembly: AssemblyLoadContext.Default.LoadFromAssemblyPath(input.DllPath), Docs: new XmlDocs(input.XmlPath))).ToArray();
            WriteLanguage(root, loaded, Zh);
            WriteLanguage(root, loaded, En);

            Console.WriteLine($"Generated bilingual API reference for {loaded.Sum(item => item.Assembly.GetExportedTypes().Length)} public types.");
            return 0;
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception);
            return 1;
        }
    }

    private static AssemblyInput Input(string root, string name, string relativeProjectDirectory, string configuration, string targetFramework)
    {
        var output = Path.Combine(root, relativeProjectDirectory.Replace('/', Path.DirectorySeparatorChar), "bin", "x64", configuration, targetFramework);
        return new AssemblyInput(name, Path.Combine(output, name + ".dll"), Path.Combine(output, name + ".xml"));
    }

    private static Dictionary<string, string> ParseArgs(string[] args)
    {
        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (var i = 0; i < args.Length; i++)
        {
            if (!args[i].StartsWith("--", StringComparison.Ordinal)) continue;
            var key = args[i][2..];
            var value = i + 1 < args.Length && !args[i + 1].StartsWith("--", StringComparison.Ordinal) ? args[++i] : "true";
            result[key] = value;
        }
        return result;
    }

    private static void WriteLanguage(string root, (AssemblyInput Input, Assembly Assembly, XmlDocs Docs)[] loaded, Language language)
    {
        var apiRoot = Path.Combine(root, "docs", language.Code, "api");
        var referenceRoot = Path.Combine(apiRoot, "reference");
        if (Directory.Exists(referenceRoot)) Directory.Delete(referenceRoot, true);
        Directory.CreateDirectory(referenceRoot);

        var index = new StringBuilder();
        index.AppendLine("# " + language.ApiTitle).AppendLine();
        index.AppendLine(language.GeneratedNotice).AppendLine();
        index.AppendLine(language.IndexIntro).AppendLine();

        var totalTypes = 0;
        var totalMembers = 0;
        foreach (var item in loaded)
        {
            var types = item.Assembly.GetExportedTypes()
                .Where(type => type.IsPublic || type.IsNestedPublic)
                .OrderBy(type => type.Namespace, StringComparer.Ordinal)
                .ThenBy(type => type.Name, StringComparer.Ordinal)
                .ToArray();

            totalTypes += types.Length;
            index.AppendLine("## " + item.Input.Name).AppendLine();
            foreach (var type in types)
            {
                var members = CountMembers(type);
                totalMembers += members;
                var file = SafeFileName(type) + ".md";
                index.AppendLine($"- [`{DisplayType(type)}`](reference/{file}) — {members}");
                File.WriteAllText(Path.Combine(referenceRoot, file), RenderType(item.Input.Name, type, item.Docs, language), new UTF8Encoding(false));
            }
            index.AppendLine();
        }

        index.Insert(index.ToString().IndexOf(language.IndexIntro, StringComparison.Ordinal) + language.IndexIntro.Length,
            $"\n\n- **{language.TypeCountLabel}:** {totalTypes}\n- **{language.MemberCountLabel}:** {totalMembers}");
        Directory.CreateDirectory(apiRoot);
        File.WriteAllText(Path.Combine(apiRoot, "README.md"), index.ToString(), new UTF8Encoding(false));
    }

    private static string RenderType(string assemblyName, Type type, XmlDocs docs, Language language)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# " + DisplayType(type)).AppendLine();
        builder.AppendLine($"- **{language.AssemblyLabel}:** `{assemblyName}.dll`");
        builder.AppendLine($"- **{language.NamespaceLabel}:** `{type.Namespace ?? "(global)"}`");
        if (type.BaseType is not null && type.BaseType != typeof(object) && !type.IsEnum)
            builder.AppendLine($"- **{language.InheritedLabel}:** `{DisplayType(type.BaseType)}`");
        builder.AppendLine();
        builder.AppendLine("## " + language.DeclarationLabel).AppendLine();
        builder.AppendLine("```csharp").AppendLine(TypeDeclaration(type)).AppendLine("```").AppendLine();
        builder.AppendLine("## " + language.DescriptionLabel).AppendLine();
        builder.AppendLine(DescriptionOrFallback(docs.Type(type), language.FallbackTypeDescription)).AppendLine();

        if (type.IsEnum)
        {
            RenderFields(builder, type, docs, language, enumOnly: true);
            return builder.ToString();
        }

        RenderConstructors(builder, type, docs, language);
        RenderProperties(builder, type, docs, language);
        RenderEvents(builder, type, docs, language);
        RenderMethods(builder, type, docs, language);
        RenderFields(builder, type, docs, language, enumOnly: false);
        return builder.ToString();
    }

    private static void RenderConstructors(StringBuilder builder, Type type, XmlDocs docs, Language language)
    {
        var values = type.GetConstructors(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).OrderBy(Signature).ToArray();
        RenderMethodsCore(builder, type, values, docs, language, language.ConstructorsLabel);
    }

    private static void RenderMethods(StringBuilder builder, Type type, XmlDocs docs, Language language)
    {
        var values = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(method => !method.IsSpecialName)
            .OrderBy(method => method.Name, StringComparer.Ordinal)
            .ThenBy(Signature)
            .Cast<MethodBase>()
            .ToArray();
        RenderMethodsCore(builder, type, values, docs, language, language.MethodsLabel);
    }

    private static void RenderMethodsCore(StringBuilder builder, Type type, MethodBase[] values, XmlDocs docs, Language language, string heading)
    {
        builder.AppendLine("## " + heading).AppendLine();
        if (values.Length == 0) { builder.AppendLine(language.NoneText).AppendLine(); return; }
        foreach (var value in values)
        {
            builder.AppendLine("### `" + MemberTitle(value) + "`").AppendLine();
            builder.AppendLine(DescriptionOrFallback(docs.Method(type, value), language.FallbackMemberDescription)).AppendLine();
            builder.AppendLine("```csharp").AppendLine(Signature(value)).AppendLine("```").AppendLine();
            var parameters = value.GetParameters();
            if (parameters.Length > 0)
            {
                builder.AppendLine("**" + language.ParametersLabel + "**").AppendLine();
                foreach (var parameter in parameters)
                    builder.AppendLine($"- `{parameter.Name}` — `{DisplayType(parameter.ParameterType)}`{DefaultValue(parameter)}");
                builder.AppendLine();
            }
            if (value is MethodInfo method)
            {
                builder.AppendLine($"**{language.ReturnsLabel}:** `{DisplayType(method.ReturnType)}`").AppendLine();
            }
        }
    }

    private static void RenderProperties(StringBuilder builder, Type type, XmlDocs docs, Language language)
    {
        var values = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .OrderBy(property => property.Name, StringComparer.Ordinal).ToArray();
        builder.AppendLine("## " + language.PropertiesLabel).AppendLine();
        if (values.Length == 0) { builder.AppendLine(language.NoneText).AppendLine(); return; }
        foreach (var value in values)
        {
            var access = (value.CanRead, value.CanWrite) switch { (true, true) => "{ get; set; }", (true, false) => "{ get; }", _ => "{ set; }" };
            builder.AppendLine("### `" + value.Name + "`").AppendLine();
            builder.AppendLine(DescriptionOrFallback(docs.Property(type, value), language.FallbackMemberDescription)).AppendLine();
            builder.AppendLine("```csharp").AppendLine($"public {DisplayType(value.PropertyType)} {value.Name} {access}").AppendLine("```").AppendLine();
        }
    }

    private static void RenderEvents(StringBuilder builder, Type type, XmlDocs docs, Language language)
    {
        var values = type.GetEvents(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .OrderBy(value => value.Name, StringComparer.Ordinal).ToArray();
        builder.AppendLine("## " + language.EventsLabel).AppendLine();
        if (values.Length == 0) { builder.AppendLine(language.NoneText).AppendLine(); return; }
        foreach (var value in values)
        {
            builder.AppendLine("### `" + value.Name + "`").AppendLine();
            builder.AppendLine(DescriptionOrFallback(docs.Event(type, value), language.FallbackMemberDescription)).AppendLine();
            builder.AppendLine("```csharp").AppendLine($"public event {DisplayType(value.EventHandlerType ?? typeof(Delegate))} {value.Name};").AppendLine("```").AppendLine();
        }
    }

    private static void RenderFields(StringBuilder builder, Type type, XmlDocs docs, Language language, bool enumOnly)
    {
        var values = type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(field => enumOnly ? field.IsLiteral : !field.IsSpecialName)
            .OrderBy(field => field.Name, StringComparer.Ordinal).ToArray();
        builder.AppendLine("## " + language.FieldsLabel).AppendLine();
        if (values.Length == 0) { builder.AppendLine(language.NoneText).AppendLine(); return; }
        foreach (var value in values)
        {
            var literal = value.IsLiteral ? $" = {value.GetRawConstantValue()}" : string.Empty;
            builder.AppendLine($"- `{value.Name}` — `{DisplayType(value.FieldType)}`{literal} — {DescriptionOrFallback(docs.Field(type, value), language.FallbackMemberDescription)}");
        }
        builder.AppendLine();
    }

    private static int CountMembers(Type type) =>
        type.GetConstructors(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).Length +
        type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly).Length +
        type.GetEvents(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly).Length +
        type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly).Count(method => !method.IsSpecialName) +
        type.GetFields(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly).Count(field => type.IsEnum ? field.IsLiteral : !field.IsSpecialName);

    private static string TypeDeclaration(Type type)
    {
        if (type.IsEnum) return $"public enum {DisplayType(type)}";
        if (type.IsInterface) return $"public interface {DisplayType(type)}";
        if (type.IsValueType) return $"public {(type.IsByRefLike ? "ref " : string.Empty)}struct {DisplayType(type)}";
        var modifier = type.IsAbstract && type.IsSealed ? "static " : type.IsAbstract ? "abstract " : type.IsSealed ? "sealed " : string.Empty;
        return $"public {modifier}class {DisplayType(type)}";
    }

    private static string Signature(MethodBase method)
    {
        var modifiers = method.IsStatic ? "static " : string.Empty;
        var parameters = string.Join(", ", method.GetParameters().Select(parameter => $"{DisplayType(parameter.ParameterType)} {parameter.Name}{DefaultValue(parameter)}"));
        if (method.IsConstructor) return $"public {method.DeclaringType?.Name}({parameters})";
        var info = (MethodInfo)method;
        var generic = method.IsGenericMethodDefinition ? "<" + string.Join(", ", method.GetGenericArguments().Select(argument => argument.Name)) + ">" : string.Empty;
        return $"public {modifiers}{DisplayType(info.ReturnType)} {method.Name}{generic}({parameters})";
    }

    private static string MemberTitle(MethodBase method) => method.IsConstructor ? method.DeclaringType?.Name ?? "ctor" : method.Name;
    private static string DescriptionOrFallback(string value, string fallback) => string.IsNullOrWhiteSpace(value) ? fallback : value;

    private static string DefaultValue(ParameterInfo parameter)
    {
        if (!parameter.HasDefaultValue) return string.Empty;
        if (parameter.DefaultValue is null) return " = null";
        if (parameter.DefaultValue is string text) return " = \"" + text.Replace("\"", "\\\"") + "\"";
        if (parameter.DefaultValue is bool flag) return flag ? " = true" : " = false";
        return " = " + Convert.ToString(parameter.DefaultValue, System.Globalization.CultureInfo.InvariantCulture);
    }

    private static string DisplayType(Type type)
    {
        if (type.IsByRef) return "ref " + DisplayType(type.GetElementType()!);
        if (type.IsArray) return DisplayType(type.GetElementType()!) + "[]";
        if (type.IsGenericParameter) return type.Name;
        var nullable = Nullable.GetUnderlyingType(type);
        if (nullable is not null) return DisplayType(nullable) + "?";
        var aliases = new Dictionary<Type, string>
        {
            [typeof(void)] = "void", [typeof(bool)] = "bool", [typeof(byte)] = "byte", [typeof(short)] = "short",
            [typeof(int)] = "int", [typeof(long)] = "long", [typeof(float)] = "float", [typeof(double)] = "double",
            [typeof(decimal)] = "decimal", [typeof(char)] = "char", [typeof(string)] = "string", [typeof(object)] = "object"
        };
        if (aliases.TryGetValue(type, out var alias)) return alias;
        if (!type.IsGenericType) return type.Name;
        var name = type.Name[..type.Name.IndexOf('`')];
        return name + "<" + string.Join(", ", type.GetGenericArguments().Select(DisplayType)) + ">";
    }

    private static string SafeFileName(Type type)
    {
        var value = (type.FullName ?? type.Name).Replace('+', '.');
        foreach (var invalid in Path.GetInvalidFileNameChars()) value = value.Replace(invalid, '_');
        return value.Replace('`', '_');
    }
}
