<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>OcctNet</RootNamespace>
    <AssemblyName>OcctNet.Wpf</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OcctNet.WinForms\OcctNet.WinForms.csproj" />
  </ItemGroup>
</Project>
