namespace OcctNet;

/// <summary>Semantic role of a node in an imported XDE assembly occurrence tree.</summary>
public enum OcctAssemblyNodeKind
{
    Assembly = 0,
    Instance = 1,
    Part = 2
}

/// <summary>RGBA color retained from XDE presentation style.</summary>
public readonly record struct OcctAssemblyColor(double R, double G, double B, double A = 1.0)
{
    public double Transparency => 1.0 - Math.Clamp(A, 0.0, 1.0);
}

/// <summary>Affine 3x4 transform retained from an XDE assembly occurrence.</summary>
public readonly record struct OcctAssemblyTransform3d(
    double M00, double M01, double M02, double M03,
    double M10, double M11, double M12, double M13,
    double M20, double M21, double M22, double M23)
{
    public static OcctAssemblyTransform3d Identity => new(
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0);

    internal static OcctAssemblyTransform3d FromArray(double[]? values)
    {
        if (values is not { Length: 12 }) return Identity;
        return new(
            values[0], values[1], values[2], values[3],
            values[4], values[5], values[6], values[7],
            values[8], values[9], values[10], values[11]);
    }
}

/// <summary>Presentation style resolved by OCCT for one XDE assembly occurrence.</summary>
public readonly record struct OcctAssemblyStyle(
    bool Visible,
    OcctAssemblyColor? SurfaceColor,
    OcctAssemblyColor? CurveColor)
{
    public double Transparency => SurfaceColor?.Transparency ?? 0.0;
}

/// <summary>
/// One node of the imported XDE occurrence tree. <see cref="Id"/> is the stable XDE
/// assembly-item path generated by OCCT and does not depend on display names.
/// </summary>
public sealed class OcctAssemblyNode
{
    private readonly List<OcctAssemblyNode> _children = new();

    internal OcctAssemblyNode(
        string id,
        int index,
        int parentIndex,
        OcctAssemblyNodeKind kind,
        string name,
        string referenceName,
        OcctShape? shape,
        OcctAssemblyStyle style,
        OcctAssemblyTransform3d localTransform,
        OcctAssemblyTransform3d globalTransform)
    {
        Id = id;
        Index = index;
        ParentIndex = parentIndex;
        Kind = kind;
        Name = name;
        ReferenceName = referenceName;
        Shape = shape;
        Style = style;
        LocalTransform = localTransform;
        GlobalTransform = globalTransform;
    }

    public string Id { get; }
    public int Index { get; }
    public int ParentIndex { get; }
    public OcctAssemblyNodeKind Kind { get; }
    public string Name { get; }
    public string ReferenceName { get; }
    public OcctShape? Shape { get; }
    public OcctAssemblyStyle Style { get; }
    public OcctAssemblyTransform3d LocalTransform { get; }
    public OcctAssemblyTransform3d GlobalTransform { get; }
    public OcctAssemblyNode? Parent { get; internal set; }
    public IReadOnlyList<OcctAssemblyNode> Children => _children;

    internal void AddChild(OcctAssemblyNode child)
    {
        child.Parent = this;
        _children.Add(child);
    }
}

/// <summary>
/// First-class snapshot of a STEP/XDE assembly document. Geometry objects remain owned by
/// the importing <see cref="OcctEngine"/>, while hierarchy, occurrence transforms and XDE
/// styles are preserved independently of legacy application tags.
/// </summary>
public sealed class OcctAssemblyDocument
{
    internal OcctAssemblyDocument(
        string sourcePath,
        OcctShape primaryShape,
        IReadOnlyList<OcctAssemblyNode> nodes,
        IReadOnlyList<OcctAssemblyNode> roots)
    {
        SourcePath = sourcePath;
        PrimaryShape = primaryShape;
        Nodes = nodes;
        Roots = roots;
    }

    public string SourcePath { get; }
    public OcctShape PrimaryShape { get; }
    public IReadOnlyList<OcctAssemblyNode> Nodes { get; }
    public IReadOnlyList<OcctAssemblyNode> Roots { get; }
    public IEnumerable<OcctAssemblyNode> Assemblies => Nodes.Where(node => node.Kind == OcctAssemblyNodeKind.Assembly);
    public IEnumerable<OcctAssemblyNode> Instances => Nodes.Where(node => node.Kind == OcctAssemblyNodeKind.Instance);
    public IEnumerable<OcctAssemblyNode> Parts => Nodes.Where(node => node.Kind != OcctAssemblyNodeKind.Assembly);
}
